# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PgdbaCli < Formula
  desc "Terminal UI for PostgreSQL DBAs — interactive diagnostics directly in the terminal."
  homepage "https://github.com/liciomatos/pgdba"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/liciomatos/pgdba/releases/download/v0.2.0/pgdba-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "011b9526ffe24983b7f93a0c5423790754ba3e1445c71b9078ae1094bac97bd0"

      define_method(:install) do
        bin.install "pgdba-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/liciomatos/pgdba/releases/download/v0.2.0/pgdba-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "ca15b16fc3cd31083c1d13c0f599e1ee849323049f4df4b2b38e6829a20497e9"

      define_method(:install) do
        bin.install "pgdba-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/liciomatos/pgdba/releases/download/v0.2.0/pgdba-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "266a0d0d07818cf8b8a3370e49dd221044004d2682b38a2104ac70c670da222d"
      define_method(:install) do
        bin.install "pgdba-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liciomatos/pgdba/releases/download/v0.2.0/pgdba-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "9c8d35806fdc3576153ec0bff6e0023ae8cfd76c9a20be7f5817a3f14d147acd"
      define_method(:install) do
        bin.install "pgdba-cli"
      end
    end
  end
end
